name: meko_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  # call api
  dio: ^4.0.4
  curl_logger_dio_interceptor: ^0.0.3
  get_it: ^8.2.0

  # State management
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  equatable: ^2.0.7
  # Log
  logger: ^1.1.0

  # Data local
  hive: ^2.2.3
  shared_preferences: ^2.0.12

  # language
  intl: ^0.20.0
  intl_utils: ^2.6.1

  # Icons / Icon json
  lottie: ^2.3.2
  flutter_svg: ^1.0.3
  image_picker: ^0.8.6
  path_provider: 2.0.11
  cupertino_icons: ^1.0.2

  # Permission
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  shimmer: ^3.0.0

  # Reload page
  pull_to_refresh: ^2.0.0

  # Firebase
#  firebase_core: ^4.1.1
#  percent_indicator: ^4.2.3
#  cached_network_image: ^3.2.3
#  firebase_messaging: ^16.0.2
#  firebase_crashlytics: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Light
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
    - family: LightItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
